### ISSUE TITLE
Question around arrays vs strings

### ISSUE THREAD

**Issue by danstarns** [Codibre/fluent-accessor#1]
Hello, Cool idea 🤔

I have a question about the below code 

```ts
// With totally loss of typing
const navigator = $(['field1', 'field2', 'field3])

// Loosing the type of the result
const navigator = $<MyType>(['field1', 'field2', 'field3'])
```

Would it work the same as below
```ts
// With totally loss of typing
const navigator = $('field1.field2.field3')

// Loosing the type of the result
const navigator = $<MyType>('field1.field2.field3')
```

**Comment by Farenheith** [comment]
This could work too. I  didn't put it at first I because thought about the possibility of some extreme case where a dot could be used in the name of the function, which would require some kind of escape character, but it could be treated later with something simple like "[field.withDot].otherField"

**Comment by danstarns** [comment]
@Farenheith Cool! Thanks 😎

**Comment by Farenheith** [comment]
Hello, @danstarns!
I finally took a look at this project again and got it working somehow lol.
But the usage got a little different:
```ts
function myTest<TFIeld>(accessor: (a: MyType) => TField) {
  .... some is stuff is done here
}

// First option
const path = $<MyType>('field1', 'field2', 'field3') // Get the same accessor outside. Couldn't get it to work well if some argument is an array index
const result = myTest(path)v// Runs MyTest passing a function equivalent to (a) => a.field1.field2.field3;


// Second option
const result = myTest($('fieldArray', '1', 'subJsonField1')) // Runs MyTest passing a function equivalent to (a) => a.fieldArray[1].subJsonField1. For some reason, TypeScript resolves pretty well the arguments types of $ using contextual typing and even array index works this way;

// Third option
const path = $<MyType>().fieldArray[1].subJsonField1 // Get the same accessor outside. This way navigating even over array indexes also works
const result = myTest(path)
```

**Comment by danstarns** [comment]
@Farenheith Hey. This is cool and coming along well :) As a sidebar suggestion I'm wondering if something like `$FIRST` or `$LAST` would be useful; 

```js
const first = myTest($('fieldArray', '$FIRST', 'subJsonField1')) // a.fieldArray[0].subJsonField1.
const last = myTest($('fieldArray', '$LAST', 'subJsonField1')) // a.fieldArray[fieldArray.length -1].subJsonField1.
```

**Comment by Farenheith** [comment]
Great idea!
I'll think about how I can do the typing for it!

**Comment by Farenheith** [comment]
I came out with something nice, @danstarns !

You can do something like this:

```ts
const result = test($('cd', 0, 'a', (x) => x.c * 2))
```
So, you can pass a nested property name OR a function, so, I can have some build in operators to simplify your life, like this:

```ts
const result = test($('cd', max())
```

where max is something like this
```ts
function max<T, R = T>(mapper: (a: T) => R = identity) {
  return (arr: T[]) => arr.reduce((acc, t) => {
    const mapped = mapper(t);
    return acc === undefined || mapped > acc ? mapped : acc);
  }, undefined,
}
```
The same way, we can have others built in operations, like:

```ts
const result = test($('cd', first());
const result = test($('cd', last());
const result = test($('cd', min());
const result = test($('cd', distinct());
```

An so on!
Additionally, this template allows the user to implement custom operations too

**Comment by Farenheith** [comment]
Dang... I tried it, the code works but the typing don't :(
I found the issue in ts [here](https://github.com/microsoft/TypeScript/issues/13995)

Edit: after more investigation, find out the main problem being the one fixed in this PR
https://github.com/microsoft/TypeScript/pull/26797

Following

**Comment by Farenheith** [comment]
@danstarns thank you again for your suggestion. I just did a version with  the built in operations **baseOp.first** and **baseOp.last**, where first and last are symbols and I resolve the typing and the implementation comparing the parameter against them.
I change my typing and https://github.com/microsoft/TypeScript/pull/26797 is no issue for me, but still, I wanted to use built in function mappers as parameters, it would be more elegant, but https://github.com/microsoft/TypeScript/issues/13995 is the issue that would make the typing work bad with it :(

**Comment by danstarns** [comment]
That is a shame the typing doesn't work & thank you for sharing some good pointers.

**Comment by Farenheith** [comment]
After all... I was thinking... there is a functionality where you can receive the property list. If I could use a function as a parameter, this list would be inconsistent.
Receiving especial symbols like **first** and **last** can be treated, though.
So, I think is better to not have the option of having function mappers and just follow your original suggestion
